# Generated by Django 2.2 on 2019-11-26 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='day',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
