# Generated by Django 2.2 on 2020-01-03 01:10

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20191223_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemreporting',
            name='problem_id',
            field=models.CharField(default=reports.models.random_code, max_length=12, unique=True),
        ),
    ]
